### ISSUE TITLE
How to use Creator Suite on .bat file ? ( the replay file on op.gg)

### ISSUE THREAD

**Issue by len85245601** [SkinSpotlights/CreatorSuite-ReplayAPI#20]
Someone help me ?

**Comment by SkinSpotlights** [comment]
Should just work, if its not then you need to manually enable the Replay API.

The tool is meant to enable the Replay API if it isn't then its because your game.cfg is in a weird spot or you got 2 of them and the first one it checks sees the Replay API is already enabled.

Manually enabling replay api involves going to the League install locating all instances of game.cfg and adding "EnableReplayApi=1" under "[General]"

**Comment by len85245601** [comment]
oh it work. Thanks
